apiVersion: v1
kind: Pod
metadata:
  name: kaniko-debug
  namespace: jenkins
spec:
  restartPolicy: Never
  hostAliases:
    - ip: "10.104.20.1"          # IP của service harbor-registry
      hostnames:
        - "harbor.local"
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: IfNotPresent
    command:
      - /busybox/sh
    args:
      - -c
      - sleep infinity
    env:
      - name: DOCKER_CONFIG
        value: /kaniko/.docker
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: jenkins-workspace
        mountPath: /workspace

  - name: sleep
    image: busybox
    command: ["sh", "-c", "echo '✅ Pod alive for debug...'; sleep 3600"]

  volumes:
    - name: jenkins-workspace
      emptyDir: {}
    - name: kaniko-secret
      secret:
        secretName: harbor-cred
