apiVersion: v1
kind: Pod
metadata:
  name: kaniko-agent
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.11.0
    args:
      - "--dockerfile=/workspace/Dockerfile"
      - "--context=/workspace/"
      - "--destination=harbor.local/spring-demo/spring-demo:latest"
      - "--docker-config=/kaniko/.docker"
      - "--verbosity=debug"
    volumeMounts:
      - name: workspace
        mountPath: /workspace
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: workspace
      emptyDir: {}
    - name: kaniko-secret
      secret:
        secretName: harbor-cred
