apiVersion: v1
kind: Pod
metadata:
  name: kaniko-debug
  namespace: jenkins
spec:
  restartPolicy: Never

  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.11.0
    imagePullPolicy: IfNotPresent
    command:
      - cat
    tty: true
    env:
      - name: DOCKER_CONFIG
        value: /kaniko/.docker
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: jenkins-workspace
        mountPath: /workspace

  - name: sleep
    image: busybox
    command: ["sh", "-c", "echo '✅ Pod alive for debug...'; sleep 3600"]

  volumes:
    - name: jenkins-workspace
      emptyDir: {}
    - name: kaniko-secret
      secret:
        secretName: harbor-cred
